org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
# agp中这两项已经无效了
#android.useAndroidX=true
#android.enableJetifier=true
# Plugins and app have migrated off KGP; enable AGP built-in Kotlin
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
